### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CaesarZhao** [jo-m/VS_muejonat_walkietalkie#1]
Hello I am a China developers, this project is walkietalkie at WiFi?

Thanks

**Comment by jo-m** [comment]
yes.

**Comment by CaesarZhao** [comment]
But when I'm using can communication? Please remind me about it thank you very much : )

**Comment by jo-m** [comment]
what exactly do you mean? I do not understand.

**Comment by CaesarZhao** [comment]
I have run the program in the two sets of equipment, but does not talk.

**Comment by jo-m** [comment]
It worked for me using a nexus 5 and a nexus 7 tablet. It uses WiFi direct. Also, it "works most of the time" but is not very reliable. It was a school project on which I stopped working now.

If you want help, you will have to provide some more details, and the debugging output.

**Comment by CaesarZhao** [comment]
Only need to run the program does not need other settings? Only need to run the program does not need other settings? I will give you log hope you can help me. Thank you very much.

**Comment by jo-m** [comment]
basically setup is: 1. enable wifi on both devices 2. place them next to each other 3. they will need up to a minute to connect
4. just works

**Comment by CaesarZhao** [comment]
Thank you very much, I in the test, if there is a problem. Please help me thank you: )
